name: pokerManagement
options:
  bundleIdPrefix: com.pokermanagement
packages:
  WebRTC:
    url: https://github.com/stasel/WebRTC
    from: "140.0.0"
  Starscream:
    url: https://github.com/daltoniam/Starscream
    from: "4.0.0"
targets:
  pokerManagement:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [
        "pokerManagement",
        "pokerManagement/Views",
        "pokerManagement/Models",
        "pokerManagement/Services",
        "pokerManagement/Services/LiveActivityManager.swift"
    ]
    dependencies:
      - package: WebRTC
      - package: Starscream
      - target: PokerWidgetExtension
    info:
      path: pokerManagement/Info.plist
      properties:
        UILaunchScreen: {}
        NSSupportsLiveActivities: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
  PokerWidgetExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources: [
        "PokerWidget",
        "pokerManagement/Models/PokerSuggestionAttributes.swift"
    ]
    info:
      path: PokerWidget/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
